name: Get EPG data

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install node-fetch xml2js

      - name: Get EPG data
        run: node get-data.js
        env:
          API_URL: https://api.beetv.kz/v2/epg/program_events.json?pivot_date=2023-05-03&channel_id=323d0565-30bd-49f5-bbba-2ac39af7661a
          OUTPUT_FILE: epg.xml
